---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx-container
          ports:
            - containerPort: 80
              name: nginx-port
              protocol: TCP