# We can set limits to our pods, like how much cpu and memory it should utilize
# what is the min and max limit..
# we will request the resource(min) and set the limits(max)
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec: 
      containers:
        - image: nginx
          name: nginx-container
          ports:
             - containerPort: 80
               name: nginx-port
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"