---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
    ver: "1.0"
  ports:
    - name: webport
      port: 35000
      targetPort: 80