
#  Deamon set and Replica set are quite simimlar, But Deamon set works as an agent and create pod on each node, where replica set may create multiple-pods in single node.

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myagent-ds
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      name: agent-pod
      labels:
        app: agent
        version: v1.0
    spec:
      containers:
        - name: agent-pod
          image: alpine:3
          command:
            - sleep
            - 1d
