
---
apiVersion: v1
kind: Pod
metadata: 
  name: init-cont
spec:
  initContainers:
    - image: alpine:3
      name: init-cont1
      command:
        - sleep
        - "10"

    - image: alpine:3
      name: init-cont2
      command:
        - sleep
        - "10"

  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP