

## To Check the deployment, write another deployment with version=jenkins:2.60.3, and check the status of application, is there any downtime or not.
# We have also written readiness probe and  liveness probe.
# we have written the service in the same file.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
        version: "1.625.1"
    spec:
      containers:
        - name: jenkins
          image: jenkins:1.625.1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: webport
      port: 35000
      targetPort: 8080