

### The difference b/w thw rc and rs is rc will override the current spec. and the rs will add the new spec i.e version and keep the data(history)
---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replication-set
  labels:
    app: jenkins
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-rs-pod
      labels:
        app: jenkins
    spec:
      initContainers:
        - name: alpine
          image: alpine:3
          command:
            - ping
            - "-c"
            - "4"
            - google.com
      containers:
        - name: jenkins
          restartPolicy: Never
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP