---
apiVersion: v1      # here we have created a namespace with name "my-namespace" it is an isolated area.
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: my-namespace
spec:
  backoffLimit: 3
  manualSelector: true
  selector:
    matchLabels:
      purpose: execute
  template:
    metadata:
      name: demo-pod
      namespace: my-namespace
      labels:
        purpose: execute
    spec:
      restartPolicy: OnFailure
      containers:
        - name: download
          image: alpine:3
          command:
            - sleep
            - 60s
