# The port on each node on which this service is exposed when type is NodePort.
# Nodeport rande should be in `30000-32767`

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec: 
      containers:
        - image: nginx
          name: nginx-container
          ports:
             - containerPort: 80
               name: nginx-port
---
apiVersion: v1
kind: Service
metadata: 
  name: nodeport-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 35000
      targetPort: 80
      protocol: TCP
      nodePort: 32000